// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SqlBatchStatementSplitter.cs" company="OBeautifulCode">
//   Copyright 2016 OBeautifulCode
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Database source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Database.Recipes
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Text.RegularExpressions;

    /// <summary>
    /// Splits an SQL batch statement into individual statements.
    /// </summary>
    /// <remarks>
    /// Adapted from <a href="http://blog.stpworks.com/archive/2010/02/22/how-to-split-sql-file-by-go-statement.aspx"/>
    /// Go statement must be on its own line.  Does not work for semicolon separator.
    /// </remarks>
#if !OBeautifulCodeDatabaseRecipesProject
    [System.Diagnostics.DebuggerStepThrough]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Database", "See package version number")]
#endif
    internal class SqlBatchStatementSplitter
    {
        /// <summary>
        /// Regex pattern to split up an SQL statement
        /// </summary>
        private const string SqlStatementSeparatorRegexPattern = @"^\s*GO\s*$";

        /// <summary>
        /// Splits a batch SQL statement into individual statements.
        /// </summary>
        /// <param name="batchSql">The batch SQL to process.</param>
        /// <returns>Returns an enumerable with individual SQL statements.</returns>
        public static IEnumerable<string> SplitSqlAndRemoveEmptyStatements(string batchSql)
        {
            return Regex.Split(batchSql + "\n", SqlStatementSeparatorRegexPattern, RegexOptions.IgnoreCase | RegexOptions.Multiline).Where(statement => !string.IsNullOrWhiteSpace(statement));
        }
    }
}
